---
name: Maven Central
on:
  create:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  perform-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-11
      - uses: actions/checkout@v2
        with:
          ref: 'new-release-script' # TODO Change it back to master
          token: ${{ secrets.GITHUB_API_TOKEN }}
      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
      - name: 'Perform'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          REF: ${{ github.event.ref }}
          SECRET_FILES_PASSPHRASE: ${{ secrets.SECRET_FILES_PASSPHRASE }}
        run: |

          echo "Cutting release from ${REF}"

          sudo apt-get install -y gnupg2 gnupg-agent

          chmod +x .build/deploy.sh .build/decrypt-secrets.sh

          .build/decrypt-secrets.sh
          .build/deploy-release.sh

      - name: update deploy status
        if: always()
        uses: unacast/actions-github-deployment-status@0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
